name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta cada dÃ­a a medianoche UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: cyberiuscompany
          outputs: |
            ./output/github-snake.svg
            ./output/github-snake-dark.svg
      - name: Push the files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Actualizando animaciÃ³n de la serpiente ğŸ"
          add: "./output"
